const videoData = [
  { id: '1', 
    title: 'Present Simple and Continuous Tense', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/xcBkQ4HMGTM/hqdefault.jpg', 
    link: 'https://youtu.be/xcBkQ4HMGTM?si=GoyGpC-DiQ8ETUAo', 
    category: 'Grammar' },
  { id: '2', 
    title: 'Action and Non-Action Verbs', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/yva2DUY1ri0/hqdefault.jpg', 
    link: 'https://youtu.be/yva2DUY1ri0?si=J9mYlfA_vxQDPbZn', 
    category: 'Grammar' },
  { id: '3', 
    title: 'Frequency Adverbs and Time Expression', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/OOT2OWNX8Kw/hqdefault.jpg', 
    link: 'https://youtu.be/OOT2OWNX8Kw?si=gICK7d_0dcQg9BDE', 
    category: 'Grammar' },
  { id: '4', 
    title: 'Simple Past Tense', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/hywHxN2rKaU/hqdefault.jpg', 
    link: 'https://youtu.be/hywHxN2rKaU?si=xn41ZBsGOw4sUB_J', 
    category: 'Grammar' },
  { id: '5', 
    title: 'Regular and Irregular Verbs in the Past Simple', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/0O5QebZEOV0/hqdefault.jpg', 
    link: 'https://youtu.be/0O5QebZEOV0?si=wAqtApblU1JZ2QKQ', 
    category: 'Grammar' },
  { id: '6', 
    title: 'Past Progressive / Continuous Tense', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/XJEUsce_HNg/hqdefault.jpg', 
    link: 'https://youtu.be/XJEUsce_HNg?si=ZU_i9ysnoR_bvKds', 
    category: 'Grammar' },
  { id: '7', 
    title: 'Simple Past and Past Continuous Tense', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/47FFyJmK55w/hqdefault.jpg', 
    link: 'https://youtu.be/47FFyJmK55w?si=ZSyEvlicrqZC58UH', 
    category: 'Grammar' },
  { id: '8', 
    title: 'Future Tense', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/0g4ULHzJQm8/hqdefault.jpg', 
    link: 'https://youtu.be/0g4ULHzJQm8?si=wbfEHFYzksJSFSu2', 
    category: 'Grammar' },
  { id: '9', 
    title: 'WILL vs BE GOING TO', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/jC7CrgrQ9XA/hqdefault.jpg', 
    link: 'https://youtu.be/jC7CrgrQ9XA?si=SvEOBvYgb9tSupP2', 
    category: 'Grammar' },
  { id: '10', 
    title: 'Present Simple and Continuous Tense 2', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/PgY0zgP3tXE/hqdefault.jpg', 
    link: 'https://youtu.be/PgY0zgP3tXE?si=bBKwQzHyNWrLTC59', 
    category: 'Grammar' },
  { id: '11', 
    title: 'Reading Lesson #1', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/owcx0QrNoNU/hqdefault.jpg', 
    link: 'https://youtu.be/owcx0QrNoNU?si=4wBR013DKmPQT0Yc', 
    category: 'Reading' },
  { id: '12', 
    title: 'Reading Lesson #2', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/uxLzmTqeH6E/hqdefault.jpg', 
    link: 'https://youtu.be/uxLzmTqeH6E?si=Ug-FBX78R3yXnrZ4', 
    category: 'Reading' },
  { id: '13', 
    title: 'Reading Lesson #3', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/voj3TR4mH88/hqdefault.jpg', 
    link: 'https://youtu.be/voj3TR4mH88?si=LbUuSlx4ZBWQ8QkZ', 
    category: 'Reading' },
  { id: '14', 
    title: 'Reading Lesson #4', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/p_-3jTDFXL8/hqdefault.jpg', 
    link: 'https://youtu.be/p_-3jTDFXL8?si=kWKTl8PzIrfRXxQ5', 
    category: 'Reading' },
  { id: '15', 
    title: 'Reading Lesson #5', 
    creator: 'by MyECO', 
    image: 'https://i.ytimg.com/vi/DWidgxWuEBU/hqdefault.jpg', 
    link: 'https://youtu.be/DWidgxWuEBU?si=YDgLGlYDxBiPxgCK', 
    category: 'Reading' },
  { id: '16', 
    title: 'Small Talks #1', 
    creator: 'by English Speaking Course', 
    image: 'https://i.ytimg.com/vi/O-RSuO0UECQ/hqdefault.jpg', 
    link: 'https://youtu.be/O-RSuO0UECQ?si=2W5i6PbIFWt190QH', 
    category: 'Speaking' },
  { id: '17', 
    title: 'Small Talks #2', 
    creator: 'by English Speaking Course', 
    image: 'https://i.ytimg.com/vi/HlXzuO5qWY8/hqdefault.jpg', 
    link: 'https://youtu.be/HlXzuO5qWY8?si=I-ZBu35Yw9Mj3It5', 
    category: 'Speaking' },
  { id: '18', 
    title: 'Active and Passive Gerunds', 
    creator: 'by English with Alex', 
    image: 'https://i.ytimg.com/vi/QV_XlU1oxJg/hqdefault.jpg', 
    link: 'https://youtu.be/QV_XlU1oxJg?si=w5PVJmuKpH3ZHLAJ', 
    category: 'Grammar' },
  { id: '19', 
    title: 'Active and Passive Infinitives', 
    creator: 'by English Speaking Course', 
    image: 'https://i.ytimg.com/vi/fVlgzuhBi-I/hqdefault.jpg', 
    link: 'https://youtu.be/fVlgzuhBi-I?si=m070TalWisyhqG-m', 
    category: 'Grammar' },
  { id: '21', 
    title: 'Phrasal Verbs for Business and the Office', 
    creator: "by Adam's English Leassons", 
    image: 'https://i.ytimg.com/vi/iHpdZ8h945k/hqdefault.jpg', 
    link: 'https://youtu.be/iHpdZ8h945k?si=3mKzaKvRhvcUaa3U', 
    category: 'Vocabulary' },
  { id: '22', 
    title: 'Prepositional Phrases', 
    creator: 'English with Alex', 
    image: 'https://i.ytimg.com/vi/USPE4NTvWWA/hqdefault.jpg', 
    link: 'https://youtu.be/USPE4NTvWWA?si=rJtulOpmYdpdrgtv', 
    category: 'Vocabulary' },
  { id: '23', 
    title: 'Common Idioms', 
    creator: 'by English Speaking Course', 
    image: 'https://i.ytimg.com/vi/6QiW_7zsYsw/hqdefault.jpg', 
    link: 'https://youtu.be/6QiW_7zsYsw?si=psLeFMRalL8mKuab', 
    category: 'Vocabulary' },
  { id: '24', 
    title: 'Phrasal Verbs for Job Interviews', 
    creator: 'by English with Alex', 
    image: 'https://i.ytimg.com/vi/FWT7KTF0vpM/hqdefault.jpg', 
    link: 'https://youtu.be/FWT7KTF0vpM?si=Bib5JGBef8Lr_GNm', 
    category: 'Vocabulary' },
  { id: '26', 
    title: "Don't make this mistake on your resume!", 
    creator: 'by English with Alex', 
    image: 'https://i.ytimg.com/vi/lo0pPv8L2s0/hqdefault.jpg', 
    link: 'https://youtu.be/lo0pPv8L2s0?si=HgWHppdu0O7w7wG7', 
    category: 'Writing' },
  { id: '27', 
    title: 'Improving your creative writing', 
    creator: 'by English with Alex', 
    image: 'https://i.ytimg.com/vi/7w2DQ0JaETk/hqdefault.jpg', 
    link: 'https://youtu.be/7w2DQ0JaETk?si=oV-RXrG7WB67FSIR', 
    category: 'Writing' },
  { id: '31', 
    title: 'English Listening Practice #1', 
    creator: 'by English Speaking Course', 
    image: 'https://i.ytimg.com/vi/stpikznD5_4/hqdefault.jpg', 
    link: '', 
    category: 'Listening' },
  { id: '32', 
    title: 'English Listening Practice #2', 
    creator: 'by English Speaking Course', 
    image: 'https://i.ytimg.com/vi/6wCzTO63P40/hqdefault.jpg', 
    link: 'https://youtu.be/6wCzTO63P40?si=5Lo4wFGBUT-C5qk5', 
    category: 'Listening' },
];

export default videoData;
